### ISSUE TITLE
1-See the car

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML Template-with image source
- [x] Create CSS Template -with background colors for the field
- [x] Ensure that the field/background changes size based on screen size
- [x] User can see their Car
