### ISSUE TITLE
2-Turn the car

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add the ability to turn the car left, right, backwards and forwards
- [x] work on JS to turn car by key press and stay that way
- [x] take out unnessasary CSS 
- [x] fix bugs
