### ISSUE TITLE
3-Start the car

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] create interval that changes left/top to move car
- [x] car moves in direction it is facing
- [x] car continues to move in direction it is facing
- [x] when changing direction the direction it moves changes to match
- [x] fix errors and remove unnecessary CSS
