### ISSUE TITLE
4-Stop the car

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] clear the interval when you press the opposite direction
- [x] determine whether the car is moving and is facing
- [x] if pressing the direction it is facing then start moving
- [x] if pressing another direction then turn and stop
- [x] start moving on its own if no direction is not changed
