### ISSUE TITLE
5-Steer the Car

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] racecar can be turned while moving and continue moving
- [ ] racecar can turn while stopped and continue on that path.
- [ ] racecar can turn in place
